# Permalinks
permalink:           pretty

# Setup
title:               BMI Journal Club
tagline:
description:         'Dept. of Biomedical Informatics<br>at Emory University'
url:                 http://gdclifford.info
baseurl:    		 /bmijc 
