# Permalinks
permalink:           pretty

# Setup
title:               BMI Journal Club
description:         '<a href="https://medschool.ucsd.edu/som/dbmi/pages/default.aspx" target="_blank">Biomedical Informatics <br>at UCSD</a>'
url:                 http://nematilab.info
baseurl:    		 /bmijc 
